spring:
  datasource:
    url: jdbc:postgresql://db.docker:5432/postgres
    username: postgres
    password: postgres
    platform: postgresql
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 9000

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: xxxxxx
    key-pair-alias: servercert
    key-pair-password: xxxx

