version: '3.1'
services:

 dns:
   image: defreitas/dns-proxy-server
   sysctls:
     - net.ipv4.ip_default_ttl=66
   networks:
     - internet
   ports:
     - "5380:5380"
   environment:
     - MG_REGISTER_CONTAINER_NAMES=1
     - MG_LOG_LEVEL=WARNING
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /etc/resolv.conf:/etc/resolv.conf

 db:
   image: postgres:10
   networks:
     - internet   
   ports:
     - "5432:5432"
   environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: authserver

 
networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge